services:
  database:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: secretPassword
      MONGO_INITDB_DATABASE: realestate
    volumes:
      - ./db-init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./dump:/dump  # Монтируем папку dump с хоста в /dump в контейнере
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: secretPassword
      ME_CONFIG_MONGODB_SERVER: database  # Указываем правильное имя сервиса
    depends_on:
      - database

  web:
    build: .
    image: realestate-angularjs
    environment:
      MONGODB_URI: mongodb://user:secretPassword@database/realestate  # Убедитесь, что user/secretPassword созданы
    depends_on:
      - database
    ports:
      - 8082:5000